# Generated by Django 4.2.1 on 2023-05-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myposts', '0002_diaries_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaries',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
    ]
